export { default as Features } from './Features'
export { default as Footer } from './Footer'
export { default as Hero } from './Hero'
export { default as Highlights } from './Highlights'
export { default as Content } from './Content'
export { default as Headline } from './Headline'
export { default as FutureFeatures } from './FutureFeatures'
export { default as Team } from './Team'
